version: "3.8"

networks:
    rowles:
        external: true
        name: ${COMPOSE_NETWORK_NAME}

services:
    web:
        image: chrisrowles/test
        container_name: rowles-web
        ports:
            - "80:80"
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/html
        environment:
            - APP_ENV=development
            - APP_DEBUG=true
            - APP_CACHE=true
            - DB_HOST=${COMPOSE_DB_IP}
            - DB_USER=rowles
            - DB_PASS=password
            - DB_NAME=rowles
        networks:
            rowles:
                ipv4_address: ${COMPOSE_WEB_IP}
    database:
        image: mysql:8
        container_name: rowles-database
        ports:
            - "3306:3306"
        volumes:
            - ./migrations:/migrations
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_PASSWORD=password
            - MYSQL_USER=rowles
            - MYSQL_DATABASE=rowles
        networks:
            rowles:
                ipv4_address: ${COMPOSE_DB_IP}