version: '3.3'
services:
  web-server:
    build:
      context: ./docker/7.4
      dockerfile: Dockerfile
    image: rowles-7.4/app
    ports:
      - '8000:80'
    volumes:
      - './html/:/var/www/html/'
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql-data:/var/lib/mysql'
volumes:
  mysql-data:
