version: "3.8"
services:
    webapp:
        image: chrisrowles/rowles-php7
        build:
            context: ./docker
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=development
            - APP_DEBUG=true